# puerto de escucha
server.port=${PORT:8085}

# medio que esto quedo obsoleto, podria borrarse.
telegram.bot.enabled=true

# URL del servicio de incentivos
incentivos.url=${INCENTIVOS_URL:https://incentivos-yuse.onrender.com}

# URL del servicio de donadores y entidades
donadoresyentidades.url=${DONADORESYENTIDADES_URL:https://agusb1101-donadores-entidades.onrender.com}